GrupoCometa/Models/Suplidor.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;

namespace GrupoCometa.Models
{
    public class Suplidor
    {
        [Display(Name = "Código")]
        public int idSuplidor { get; set; }
        [Display(Name = "Empresa")]
        [StringLength(50, ErrorMessage = "<i class='fa fa-times-circle'></i> Este campo no puede exceder los {1} caracteres")]
        public string cNombre { get; set; }
        [Display(Name = "Representante")]
        [StringLength(50, ErrorMessage = "<i class='fa fa-times-circle'></i> Este campo no puede exceder los {1} caracteres")]
        public string cRepresentante { get; set; }
        [Display(Name = "E-Mail")]
        [DataType(DataType.EmailAddress)]
        [EmailAddress(ErrorMessage = "<i class='fa fa-times-circle'></i> El e-mail no contiene un formato válido")]
        [StringLength(30, ErrorMessage = "<i class='fa fa-times-circle'></i> El e-mail no puede exceder los {1} caracteres")]
        public string cEmail { get; set; }
        [Display(Name = "Teléfono")]
        [StringLength(15, ErrorMessage = "<i class='fa fa-times-circle'></i> El teléfono no puede exceder los {1} caracteres")]
        public string cTelefono { get; set; }
        [Display(Name = "Dirección")]
        [StringLength(150, ErrorMessage = "<i class='fa fa-times-circle'></i> Este campo no puede exceder los {1} caracteres")]
        public string cDireccion { get; set; }

        public List<SelectListItem> listaSuplidores { get; set; }

        /// <summary>
        /// Constuctor sin parametros 
        /// </summary>
        public Suplidor() { }

        /// <summary>
        /// Constructor con parametros
        /// </summary>
        /// <param name="idSuplidor"></param>
        public Suplidor(int idSuplidor)
        {
            Data.dsSuplidorTableAdapters.SuplidorTableAdapter Adapter = new Data.dsSuplidorTableAdapters.SuplidorTableAdapter();
            //Data.dsProductoTableAdapters.ProductosTableAdapter Adapter = new Data.dsProductoTableAdapters.ProductosTableAdapter();
            Data.dsSuplidor.SuplidorDataTable dt = Adapter.SelectSuplidor(idSuplidor);

            if (dt.Rows.Count > 0)
            {
                Data.dsSuplidor.SuplidorRow dr = dt[0];
                this.idSuplidor = dr.idSuplidor;
                if (!dr.IscNombreNull())
                    this.cNombre = dr.cNombre;
                if (!dr.IscRepresentanteNull())
                    this.cRepresentante = dr.cRepresentante;
                if (!dr.IscEmailNull())
                    this.cEmail = dr.cEmail;
                if (!dr.IscTelefonoNull())
                    this.cTelefono = dr.cTelefono;
                if (!dr.IscDireccionNull())
                    this.cDireccion = dr.cDireccion;
            }
        }

        /// <summary>
        /// Genera la lista de productos de la DB
        /// </summary>
        /// <returns></returns>
        public static List<Suplidor> GetListaSuplidores()
        {
            List<Suplidor> listaSuplidores = new List<Suplidor>();
            Data.dsSuplidorTableAdapters.SuplidorTableAdapter Adapter = new Data.dsSuplidorTableAdapters.SuplidorTableAdapter();
            Data.dsSuplidor.SuplidorDataTable dt = Adapter.SelectListaSuplidores();

            foreach (var dr in dt)
            {
                Suplidor item = new Suplidor();
                item.idSuplidor = dr.idSuplidor;
                if (!dr.IscNombreNull())
                    item.cNombre = dr.cNombre;
                if (!dr.IscRepresentanteNull())
                    item.cRepresentante = dr.cRepresentante;
                if (!dr.IscEmailNull())
                    item.cEmail = dr.cEmail;
                if (!dr.IscTelefonoNull())
                    item.cTelefono = dr.cTelefono;
                if (!dr.IscDireccionNull())
                    item.cDireccion = dr.cDireccion;

                listaSuplidores.Add(item);
            }

            return listaSuplidores;
        }


        /// <summary>
        /// Inserta el cliente a la DB
        /// </summary>
        public void InsertSuplidor()
        {
            Data.dsSuplidorTableAdapters.SuplidorTableAdapter Adapter = new Data.dsSuplidorTableAdapters.SuplidorTableAdapter();
            Adapter.InsertSuplidor(this.cNombre, this.cRepresentante, this.cEmail, this.cTelefono, this.cDireccion);
        }

        /// <summary>
        /// Actualiza el cliente a la DB
        /// </summary>
        public void UpdateSuplidor()
        {
            Data.dsSuplidorTableAdapters.SuplidorTableAdapter Adapter = new Data.dsSuplidorTableAdapters.SuplidorTableAdapter();
            Adapter.UpdateSuplidor(this.idSuplidor, this.cNombre, this.cRepresentante, this.cEmail, this.cTelefono, this.cDireccion);
        }

        /// <summary>
        /// Elimina el cliente de la DB
        /// </summary>
        /// <param name="idSuplidor"></param>
        public static void DeleteSuplidor(int idSuplidor)
        {
            Data.dsSuplidorTableAdapters.SuplidorTableAdapter Adapter = new Data.dsSuplidorTableAdapters.SuplidorTableAdapter();
            Adapter.DeleteSuplidor(idSuplidor);
        }
    }
}

GrupoCometa/Controllers/SuplidorController.cs
using GrupoCometa.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GrupoCometa.Controllers
{
    public class SuplidorController : Controller
    {
        // GET: Suplidor
        public ActionResult Index()
        {
            List<Suplidor> ListaSuplidores = new List<Suplidor>();
            ListaSuplidores = Suplidor.GetListaSuplidores();
            return View(ListaSuplidores);
        }

        // GET: Suplidor/Details/5
        public ActionResult Details(int idSuplidor)
        {
            Suplidor newModel = new Suplidor(idSuplidor);
            return View(newModel);
        }

        //GET: Producto/Insert/
        public ActionResult Insert()
        {
            Suplidor newModel = new Suplidor();
            //newModel.listaTiposProducto = Producto.GetListaTiposProducto();
            return View(newModel);
        }

        [HttpPost]
        public ActionResult Insert(Suplidor newModel)
        {
            if (ModelState.IsValid)
            {
                newModel.InsertSuplidor();
                return RedirectToAction("Index");
            }
            else
            {
                //newModel.listaSuplidor = Producto.GetListaTiposProducto();
                return View(newModel);
            }
        }



        // GET: Suplidor/Edit/5
        public ActionResult Edit(int idSuplidor)
        {
            Suplidor newModel = new Suplidor(idSuplidor);
            //newModel.listaTiposProducto = Producto.GetListaTiposProducto();
            return View(newModel);
        }

        [HttpPost]
        public ActionResult Edit(Suplidor newModel)
        {
            if (ModelState.IsValid)
            {
                newModel.UpdateSuplidor();
                return RedirectToAction("Index");
            }
            else
            {
                //newModel.listaTiposProducto = Producto.GetListaTiposProducto();
                return View(newModel);
            }
        }

        // GET: Suplidor/Delete/5
        public ActionResult Delete(int idSuplidor)
        {
            Suplidor newModel = new Suplidor(idSuplidor);
            return View(newModel);
        }

        // POST: Suplidor/Delete/5
        [HttpPost]
        public ActionResult Delete(int idSuplidor, Suplidor newModel)
        {
            Suplidor.DeleteSuplidor(idSuplidor);
            return RedirectToAction("Index");
        }
    }
}

GrupoCometa/Views/Suplidor/Delete.cshtml
@model GrupoCometa.Models.Suplidor

@{
    ViewBag.Title = "Eliminar";
}

<h2>Eliminar Producto</h2>

<h3>¿Está seguro que desea eliminar este suplidor?</h3>
<div>
    @*<h4>Suplidor</h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.idSuplidor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.idSuplidor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cNombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cNombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cRepresentante)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cRepresentante)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cTelefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cTelefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cDireccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cDireccion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-danger" />
            @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-default" })
        </div>
    }
</div>

GrupoCometa/Views/Suplidor/Details.cshtml
@model GrupoCometa.Models.Suplidor

@{
    ViewBag.Title = "Detalles";
}

<h2>Detalles del Suplidor</h2>

<div>
    @*<h4>Suplidor</h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.idSuplidor)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.idSuplidor)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cNombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cNombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cRepresentante)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cRepresentante)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cEmail)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cEmail)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cTelefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cTelefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.cDireccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cDireccion)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { idSuplidor = Model.idSuplidor }, new { @class = "btn btn-default" }) 
    @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-default" })
</p>

GrupoCometa/Views/Suplidor/Edit.cshtml
@model GrupoCometa.Models.Suplidor

@{
    ViewBag.Title = "Editar";
}

<h2>Editar Suplidor</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">Formulario de Creación de Suplidores</div>
                <div class="panel-body">

                    <div class="row form-group">
                        @Html.LabelFor(model => model.idSuplidor, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.idSuplidor, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                            @Html.ValidationMessageFor(model => model.idSuplidor, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row form-group">
                        @Html.LabelFor(model => model.cNombre, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.cNombre, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.cNombre, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row form-group">
                        @Html.LabelFor(model => model.cRepresentante, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.cRepresentante, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.cRepresentante, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row form-group">
                        @Html.LabelFor(model => model.cEmail, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.cEmail, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.cEmail, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row form-group">
                        @Html.LabelFor(model => model.cTelefono, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.cTelefono, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.cTelefono, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row form-group">
                        @Html.LabelFor(model => model.cDireccion, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.cDireccion, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.cDireccion, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-6 col-sm-offset-3">
                            <div class="btn-toolbar">
                                <input type="submit" value="Guardar Suplidor" class="btn btn-default" />
                                <button class="btn-default btn btnCancelar" type="button" onclick="window.location.href = '@Url.Action("Index", "Suplidor")';">Cancelar</button>
                            </div>
                        </div>
                    </div>
                    
                    </div>
                </div>
            </div>
        </div>
                }

               

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }

GrupoCometa/Views/Suplidor/Index.cshtml
@model IEnumerable<GrupoCometa.Models.Suplidor>

@{
    ViewBag.Title = "Suplidores";
}

<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Suplidores</h2>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">Listado de Suplidores</div>
            <div class="panel-body">
                <p>
                    @Html.ActionLink("Insertar Nuevo", "Insert", null, new { @class = "btn btn-primary" })
                </p>
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.idSuplidor)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.cNombre)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.cRepresentante)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.cEmail)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.cTelefono)
                            </th>
                            @*<th>
                                @Html.DisplayNameFor(model => model.cDireccion)
                            </th>*@
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.idSuplidor)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.cNombre)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.cRepresentante)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.cEmail)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.cTelefono)
                                </td>
                                @*<td>
                                    @Html.DisplayFor(modelItem => item.cDireccion)
                                </td>*@
                                <td>
                                    @Html.ActionLink("Editar", "Edit", new { idSuplidor = item.idSuplidor }, new { @class = "btn btn-default" }) 
                                    @Html.ActionLink("Detalles", "Details", new { idSuplidor = item.idSuplidor }, new { @class = "btn btn-default" }) 
                                    @Html.ActionLink("Eliminar", "Delete", new { idSuplidor = item.idSuplidor }, new { @class = "btn btn-default" })
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script>
        $(document).ready(function () {
            $('.table').DataTable({
                "searching": false,
                "lengthChange": false,
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.9/i18n/Spanish.json"
                }

            });
        });
    </script>
}

GrupoCometa/Views/Suplidor/Insert.cshtml
@model GrupoCometa.Models.Suplidor

@{
    ViewBag.Title = "Insertar Suplidores";
}

<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Crear Nuevo Suplidor</h2>
    </div>
</div>


@using (Html.BeginForm())
{
    
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">Formulario de Creación de Suplidores</div>
                <div class="panel-body">

                    <div class="row form-group">
                        @Html.LabelFor(model => model.cNombre, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.cNombre, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.cNombre, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row form-group">
                        @Html.LabelFor(model => model.cRepresentante, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.cRepresentante, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.cRepresentante, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row form-group">
                        @Html.LabelFor(model => model.cEmail, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.cEmail, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.cEmail, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row form-group">
                        @Html.LabelFor(model => model.cTelefono, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.cTelefono, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.cTelefono, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row form-group">
                        @Html.LabelFor(model => model.cDireccion, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.cDireccion, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.cDireccion, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-6 col-sm-offset-3">
                            <div class="btn-toolbar">
                                <input type="submit" value="Crear Suplidor" class="btn btn-default" />
                                <button class="btn-default btn btnCancelar" type="button" onclick="window.location.href = '@Url.Action("Index", "Suplidor")';">Cancelar</button>
                            </div>
                        </div>
                    </div>

                    </div>
                </div>
            </div>
                </div>
                }

                

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }