GrupoCometa/Models/CuentasPorCobrar.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;

namespace GrupoCometa.Models
{
    public class CuentasPorCobrar
    {
        [Display(Name = "Código")]
        public int idTransaccion { get; set; }
        [Display(Name = "Clave de Factura")]
        public int idFacturaHeader { get; set; }
        [Display(Name = "Balance de Cuenta")]
        [DataType(DataType.Currency)]
        public decimal mBalance { get; set; }

        public List<SelectListItem>  listaFacturaHeader { get; set; }

        /// <summary>
        /// Constuctor sin parametros 
        /// </summary>
        public CuentasPorCobrar() { }

        /// <summary>
        /// Constructor con parametros
        /// </summary>
        /// <param name="idTransaccion"></param>
        public CuentasPorCobrar(int idTransaccion)
        {
            Data.dsCuentasTableAdapters.CuentasPorCobrarTableAdapter Adapter = new Data.dsCuentasTableAdapters.CuentasPorCobrarTableAdapter();
            //Data.dsProductoTableAdapters.ProductosTableAdapter Adapter = new Data.dsProductoTableAdapters.ProductosTableAdapter();
            Data.dsCuentas.CuentasPorCobrarDataTable dt = Adapter.SelectCPC(idTransaccion);

            if (dt.Rows.Count > 0)
            {
                Data.dsCuentas.CuentasPorCobrarRow dr = dt[0];
                this.idTransaccion = dr.idTransaccion;
                if (!dr.IsidFacturaHeaderNull())
                    this.idFacturaHeader = dr.idFacturaHeader;
                this.mBalance = dr.mBalance;
            }
        }

        public static List<CuentasPorCobrar> GetListaCuentasPorCobrar()
        {
            List<CuentasPorCobrar> listaCuentasPorCobrar = new List<CuentasPorCobrar>();
            Data.dsCuentasTableAdapters.CuentasPorCobrarTableAdapter Adapter = new Data.dsCuentasTableAdapters.CuentasPorCobrarTableAdapter();
            Data.dsCuentas.CuentasPorCobrarDataTable dt = Adapter.SelectListaCPC();

            foreach (var dr in dt)
            {
                CuentasPorCobrar item = new CuentasPorCobrar();
                item.idTransaccion = dr.idTransaccion;
                if (!dr.IsidFacturaHeaderNull())
                    item.idFacturaHeader = dr.idFacturaHeader;
                if (!dr.IsmBalanceNull())
                    item.mBalance = dr.mBalance;
                
                listaCuentasPorCobrar.Add(item);
            }

            return listaCuentasPorCobrar;
        }

        public static List<SelectListItem> GetListaFacturaHeader()
        {
            List<SelectListItem> listaFacturaHeader = new List<SelectListItem>();
            Data.dsCuentasTableAdapters.FacturasHeaderTableAdapter Adapter = new Data.dsCuentasTableAdapters.FacturasHeaderTableAdapter();
            Data.dsCuentas.FacturasHeaderDataTable dt = Adapter.SelectListaFacturasHeader(null);

            foreach (var dr in dt)
            {
                SelectListItem item = new SelectListItem();
                item.Value = dr.idFacturaHeader.ToString();
                item.Text = "[" + dr.idFacturaHeader.ToString() + "] - " + dr.cEmpresa;
                listaFacturaHeader.Add(item);
            }

            return listaFacturaHeader;
        }

        /// <summary>
        /// Inserta el cliente a la DB
        /// </summary>
        public void InsertCuentasPorCobrar()
        {
            Data.dsCuentasTableAdapters.CuentasPorCobrarTableAdapter Adapter =
                new Data.dsCuentasTableAdapters.CuentasPorCobrarTableAdapter();
            Adapter.InsertCPC(this.idFacturaHeader, this.mBalance);

        }

        /// <summary>
        /// Actualiza el inventario a la DB
        /// </summary>
        public void UpdateCuentasPorCobrar()
        {
            Data.dsCuentasTableAdapters.CuentasPorCobrarTableAdapter Adapter =
                new Data.dsCuentasTableAdapters.CuentasPorCobrarTableAdapter();
            Adapter.UpdateCPC(this.idTransaccion, this.idFacturaHeader, this.mBalance);
        }

        /// <summary>
        /// Elimina el elemento de la DB
        /// </summary>
        /// <param name="idInventario"></param>
        public static void DeleteCuentasPorCobrar(int idTransaccion)
        {
            Data.dsCuentasTableAdapters.CuentasPorCobrarTableAdapter Adapter =
                new Data.dsCuentasTableAdapters.CuentasPorCobrarTableAdapter();
            Adapter.DeleteCPC(idTransaccion);
        }
    }
}

GrupoCometa/Controllers/CuentasPorCobrarController.cs
using GrupoCometa.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GrupoCometa.Controllers
{
    public class CuentasPorCobrarController : Controller
    {
        // GET: CuentasPorCobrar
        public ActionResult Index()
        {
            List<CuentasPorCobrar> ListaCuentasPorCobrar = new List<CuentasPorCobrar>();
            ListaCuentasPorCobrar = CuentasPorCobrar.GetListaCuentasPorCobrar();
            return View(ListaCuentasPorCobrar);
        }

        // GET: CuentasPorCobrar/Details/5
        public ActionResult Details(int idTransaccion)
        {
            CuentasPorCobrar newModel = new CuentasPorCobrar(idTransaccion);
            return View(newModel);
        }

        // GET: CuentasPorCobrar/Insert
        public ActionResult Insert()
        {
            CuentasPorCobrar newModel = new CuentasPorCobrar();
            newModel.listaFacturaHeader = CuentasPorCobrar.GetListaFacturaHeader();
            return View(newModel);
        }

        [HttpPost]
        public ActionResult Insert(CuentasPorCobrar newModel)
        {
            if (ModelState.IsValid)
            {
                newModel.InsertCuentasPorCobrar();
                return RedirectToAction("Index");
            }
            else
            {
                newModel.listaFacturaHeader = CuentasPorCobrar.GetListaFacturaHeader();
                return View(newModel);
            }
        }

        // GET: CuentasPorCobrar/Edit/5
        public ActionResult Edit(int idTransaccion)
        {
            CuentasPorCobrar newModel = new CuentasPorCobrar(idTransaccion);
            newModel.listaFacturaHeader = CuentasPorCobrar.GetListaFacturaHeader();
            return View(newModel);
        }

        // POST: CuentasPorCobrar/Edit/5
        [HttpPost]
        public ActionResult Edit(CuentasPorCobrar newModel)
        {
            if (ModelState.IsValid)
            {
                newModel.UpdateCuentasPorCobrar();
                return RedirectToAction("Index");
            }
            else
            {
                newModel.listaFacturaHeader = CuentasPorCobrar.GetListaFacturaHeader();
                return View(newModel);
            }
        }

        // GET: CuentasPorCobrar/Delete/5
        public ActionResult Delete(int idTransaccion)
        {
            CuentasPorCobrar newModel = new CuentasPorCobrar(idTransaccion);
            return View(newModel);
        }

        // POST: CuentasPorCobrar/Delete/5
        [HttpPost]
        public ActionResult Delete(int idTransaccion, CuentasPorCobrar newModel)
        {
            Inventario.DeleteInventario(idTransaccion);
            return RedirectToAction("Index");
        }
    }
}

GrupoCometa/Views/CuentasPorCobrar/Delete.cshtml
@model GrupoCometa.Models.CuentasPorCobrar

@{
    ViewBag.Title = "Delete";
}

<h2>Eliminar</h2>

<h3>¿Está seguro que desea eliminar este elemento?</h3>
<div>
    @*<h4>Cuentas Por Cobrar</h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.idTransaccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.idTransaccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.idFacturaHeader)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.idFacturaHeader)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mBalance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mBalance)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        @Html.HiddenFor(model => model.idTransaccion)
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> 
            @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-default" })
        </div>
    }
</div>

GrupoCometa/Views/CuentasPorCobrar/Details.cshtml
@model GrupoCometa.Models.CuentasPorCobrar

@{
    ViewBag.Title = "Detalles";
}

<h2>Detalles</h2>

<div>
    @*<h4>Cuentas Por Cobrar</h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.idTransaccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.idTransaccion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.idFacturaHeader)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.idFacturaHeader)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.mBalance)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.mBalance)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { idTransaccion = Model.idTransaccion }, new { @class = "btn btn-default" })
    @Html.ActionLink("Volver", "Index", null, new { @class = "btn btn-default" })
</p>

GrupoCometa/Views/CuentasPorCobrar/Edit.cshtml
@model GrupoCometa.Models.CuentasPorCobrar

@{
    ViewBag.Title = "Editar";
}
<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Editar Cuenta por Cobrar</h2>
    </div>
</div>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">Formulario de Edición de Cuentas por Cobrar</div>
                <div class="panel-body">


                    <div class="row form-group">
                        @Html.LabelFor(model => model.idTransaccion, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.idTransaccion, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                            @Html.ValidationMessageFor(model => model.idTransaccion, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row form-group">
                        @Html.LabelFor(model => model.idFacturaHeader, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.idFacturaHeader, Model.listaFacturaHeader, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.idFacturaHeader, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row form-group">
                        @Html.LabelFor(model => model.mBalance, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.mBalance, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.mBalance, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-6 col-sm-offset-3">
                            <div class="btn-toolbar">
                                <input type="submit" value="Guardar Cuenta" class="btn btn-default" />
                                <button class="btn-default btn btnCancelar" type="button" onclick="window.location.href = '@Url.Action("Index", "CuentasPorCobrar")';">Cancelar</button>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
}
                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }

GrupoCometa/Views/CuentasPorCobrar/Index.cshtml
@model IEnumerable<GrupoCometa.Models.CuentasPorCobrar>

@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Cuentas por Cobrar</h2>
    </div>
</div>


<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">Listado de Mercancía en Inventario</div>
            <div class="panel-body">
                <p>
                    @Html.ActionLink("Insertar Nuevo", "Insert", null, new { @class = "btn btn-primary" })
                </p>
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.idTransaccion)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.idFacturaHeader)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.mBalance)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.idTransaccion)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.idFacturaHeader)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.mBalance)
                                </td>
                                <td>
                                    @Html.ActionLink("Editar", "Edit", new {idTransaccion = item.idTransaccion}, new { @class = "btn btn-default" }) 
                                    @Html.ActionLink("Detalles", "Details", new { idTransaccion = item.idTransaccion }, new { @class = "btn btn-default" }) 
                                    @Html.ActionLink("Eliminar", "Delete", new { idTransaccion = item.idTransaccion }, new { @class = "btn btn-default" })
                                </td>
                            </tr>
                        }
                    </tbody>

                </table>
            </div>
        </div>
    </div>
</div>

@section scripts
{
    <script>
        $(document).ready(function () {
            $('.table').DataTable({
                "searching": false,
                "lengthChange": false,
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/1.10.9/i18n/Spanish.json"
                }

            });
        });
    </script>
}

GrupoCometa/Views/CuentasPorCobrar/Insert.cshtml
@model GrupoCometa.Models.CuentasPorCobrar

@{
    ViewBag.Title = "Insertar";
}

<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Crear Nueva Cuenta por Cobrar</h2>
    </div>
</div>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">Formulario de Creación de Cuentas por Cobrar</div>
                <div class="panel-body">

                    <div class="row form-group">
                        @Html.LabelFor(model => model.idTransaccion, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.idTransaccion, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly" } })
                            @Html.ValidationMessageFor(model => model.idTransaccion, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row form-group">
                        @Html.LabelFor(model => model.idFacturaHeader, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.idFacturaHeader, Model.listaFacturaHeader, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.idFacturaHeader, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row form-group">
                        @Html.LabelFor(model => model.mBalance, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.mBalance, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.mBalance, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-6 col-sm-offset-3">
                            <div class="btn-toolbar">
                                <input type="submit" value="Crear Cuenta" class="btn btn-default" />
                                <button class="btn-default btn btnCancelar" type="button" onclick="window.location.href = '@Url.Action("Index", "CuentasPorCobrar")';">Cancelar</button>
                            </div>
                        </div>
                    </div>

                    </div>
                </div>
            </div>
                </div>
                }

                

                @section Scripts {
                    @Scripts.Render("~/bundles/jqueryval")
                }